version: "3"
services:
  client:
    image: "9873907098/multi-client"
    mem_limit: 128m
    hostname: client 
  redis:
    image: redis:latest
  server:
    image: "9873907098/multi-server"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "9873907098/multi-worker"
    hostname: worker
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "9873907098/multi-nginx"
    hostname: nginx
    mem_limit: 128m
    ports:
      - '80:80'



